export enum IconUnicode {
	noteunicode = 'e675',
	searchunicode = 'e693',
	editV2unicode = 'e6b0',
	motorcycleunicode = 'e701',
	brokenlineunicode = 'e629',
	borrowunicode = 'e661',
	medicalunicode = 'e64d',
	waterunicode = 'e66c',
	learnunicode = 'e607',
	smokeunicode = 'e60d',
	relaxunicode = 'e698',
	entertainmentunicode = 'e699',
	complexunicode = 'e69e',
	foodunicode = 'e6e8',
	Snacksunicode = 'e644',
	travelunicode = 'e645',
	houseunicode = 'e646',
	letterunicode = 'e647',
	restaurantunicode = 'e64f',
	editunicode = 'e653',
	gldcoinsunicode = 'e65b',
	busunicode = 'e658',
	eyeopenunicode = 'e7f4',
	eyecloseunicode = 'e7b3',
	gldcoinsv2unicode = 'e662',
	xingchengunicode = 'e674',
	gobackunicode = 'e6ff',
	washinunicode = 'e67d',
	shopingunicode = 'e680',
	thinkunicode = 'e68d',
	deleteunicode = 'e68e',
	settingunicode = 'e68f',
	phoneunicode = 'e692',
	menuunicode = 'e6b7',
	redpaketunicode = 'e6dd',
	wageunicode = 'e6de',
	jianyuedeunicode = 'e6df',
}
export enum IconType {
	note = 'youji',
	search = 'sousuo',
	editV2 = 'bianji',
	motorcycle = 'motuo',
	brokenline = 'touzi',
	borrow = 'jiekuanshenqing',
	water = 'shuidian1',
	medical = 'yiliao',
	learn = 'xuexi',
	smoke = 'yanjiutangcha',
	relax = 'youxian',
	entertainment = 'yule',
	complex = 'zonghe',
	food = 'wucan',
	snacks = 'canyin',
	travel = 'jingdian',
	house = 'zhusu',
	letter = 'duanxin',
	restaurant = 'canting',
	edit = 'dianping',
	bus = 'gongjiaoche',
	glodcoins = 'huobiduihuan',
	eyeopen = 'attention_light',
	eyeclose = 'attentionforbidfill',
	glodcoinsv2 = 'qian',
	xingcheng = 'xingcheng',
	washin = 'xiyiji',
	shoping = 'gouwu',
	think = 'renwen',
	delete = 'shanchu',
	setting = 'shezhi',
	phone = 'shouji',
	menu = 'xitongcaidan',
	redpaket = 'dixiaofei',
	wage = 'gaoxiaofei',
	jianyuede = 'jianyuede',
	goback = 'fanhui',
}
export const IconTypeArr = [
	'note',
	'search',
	'editV2',
	'motorcycle',
	'brokenline',
	'borrow',
	'water',
	'medical',
	'learn',
	'smoke',
	'relax',
	'entertainment',
	'complex',
	'food',
	'snacks',
	'travel',
	'house',
	'letter',
	'restaurant',
	'edit',
	'bus',
	'glodcoins',
	'eyeopen',
	'glodcoinsv2',
	'xingcheng',
	'washin',
	'shoping',
	'think',
	'delete',
	'setting',
	'phone',
	'menu',
	'redpaket',
	'wage',
	'jianyuede',
	'goback',
]
export enum IconSize {
	small = 'small',
	big = 'big',
	normal = 'normal',
}
export const IconSizeArr = ['small', 'big', 'normal']
